// <auto-generated />
using FinalFantasy.RepositoryEF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FinalFantasy.RepositoryEF.Migrations
{
    [DbContext(typeof(GameFFContext))]
    partial class GameFFContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FinalFantasy.Core.Entities.Hero", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("LevelID")
                        .HasColumnType("int");

                    b.Property<int>("Life")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("WeaponID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("LevelID");

                    b.HasIndex("UserID");

                    b.HasIndex("WeaponID");

                    b.ToTable("Hero");
                });

            modelBuilder.Entity("FinalFantasy.Core.Entities.Level", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Level");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Level 1"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Level 2"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Level 3"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Level 4"
                        },
                        new
                        {
                            ID = 5,
                            Name = "Level 5"
                        });
                });

            modelBuilder.Entity("FinalFantasy.Core.Entities.Monster", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("LevelID")
                        .HasColumnType("int");

                    b.Property<int>("Life")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WeaponID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("LevelID");

                    b.HasIndex("WeaponID");

                    b.ToTable("Monster");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            LevelID = 1,
                            Life = 20,
                            Name = "Fantasma1",
                            Type = "Ghost",
                            WeaponID = 1
                        },
                        new
                        {
                            ID = 2,
                            LevelID = 2,
                            Life = 40,
                            Name = "Fantasma2",
                            Type = "Ghost",
                            WeaponID = 2
                        },
                        new
                        {
                            ID = 3,
                            LevelID = 5,
                            Life = 100,
                            Name = "Lucifer1",
                            Type = "Lucifer",
                            WeaponID = 1
                        },
                        new
                        {
                            ID = 4,
                            LevelID = 3,
                            Life = 60,
                            Name = "Lucifer2",
                            Type = "Lucifer",
                            WeaponID = 2
                        },
                        new
                        {
                            ID = 5,
                            LevelID = 4,
                            Life = 80,
                            Name = "Lucifer3",
                            Type = "Lucifer",
                            WeaponID = 3
                        },
                        new
                        {
                            ID = 6,
                            LevelID = 5,
                            Life = 100,
                            Name = "Lucifer4",
                            Type = "Lucifer",
                            WeaponID = 4
                        });
                });

            modelBuilder.Entity("FinalFantasy.Core.Entities.User", b =>
                {
                    b.Property<string>("Nickname")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Nickname");

                    b.ToTable("User");
                });

            modelBuilder.Entity("FinalFantasy.Core.Entities.Weapon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Name")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Weapon");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = 0
                        },
                        new
                        {
                            ID = 2,
                            Name = 1
                        },
                        new
                        {
                            ID = 3,
                            Name = 2
                        },
                        new
                        {
                            ID = 4,
                            Name = 3
                        },
                        new
                        {
                            ID = 5,
                            Name = 4
                        },
                        new
                        {
                            ID = 6,
                            Name = 5
                        },
                        new
                        {
                            ID = 7,
                            Name = 6
                        },
                        new
                        {
                            ID = 8,
                            Name = 7
                        },
                        new
                        {
                            ID = 9,
                            Name = 8
                        },
                        new
                        {
                            ID = 10,
                            Name = 9
                        },
                        new
                        {
                            ID = 11,
                            Name = 10
                        },
                        new
                        {
                            ID = 12,
                            Name = 11
                        });
                });

            modelBuilder.Entity("FinalFantasy.Core.Entities.Hero", b =>
                {
                    b.HasOne("FinalFantasy.Core.Entities.Level", "Level")
                        .WithMany("Heroes")
                        .HasForeignKey("LevelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinalFantasy.Core.Entities.User", "User")
                        .WithMany("Heroes")
                        .HasForeignKey("UserID");

                    b.HasOne("FinalFantasy.Core.Entities.Weapon", "Weapon")
                        .WithMany("Heroes")
                        .HasForeignKey("WeaponID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Level");

                    b.Navigation("User");

                    b.Navigation("Weapon");
                });

            modelBuilder.Entity("FinalFantasy.Core.Entities.Monster", b =>
                {
                    b.HasOne("FinalFantasy.Core.Entities.Level", "Level")
                        .WithMany("Monsters")
                        .HasForeignKey("LevelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinalFantasy.Core.Entities.Weapon", "Weapon")
                        .WithMany("Monsters")
                        .HasForeignKey("WeaponID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Level");

                    b.Navigation("Weapon");
                });

            modelBuilder.Entity("FinalFantasy.Core.Entities.Level", b =>
                {
                    b.Navigation("Heroes");

                    b.Navigation("Monsters");
                });

            modelBuilder.Entity("FinalFantasy.Core.Entities.User", b =>
                {
                    b.Navigation("Heroes");
                });

            modelBuilder.Entity("FinalFantasy.Core.Entities.Weapon", b =>
                {
                    b.Navigation("Heroes");

                    b.Navigation("Monsters");
                });
#pragma warning restore 612, 618
        }
    }
}
